name:                answers-script
version:             0.1.0.0
github:              "githubuser/answers-script"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/answers-script#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- cryptohash-sha1
- directory-tree
- containers
- aeson
- pcre-heavy
- pcre-light
- bytestring
- utf8-string
- base16-bytestring
- pandoc
- text
- lens

library:
  source-dirs: src

executables:
  answers-script-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - answers-script

tests:
  answers-script-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - answers-script
    - hspec
    - QuickCheck
